// <auto-generated />
using System;
using LanceFlow.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LanceFlow.Migrations
{
    [DbContext(typeof(DcContext))]
    [Migration("20210107115725_AddCompanyMigration")]
    partial class AddCompanyMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LanceFlow.Models.Entities.DanniePoFurmam", b =>
                {
                    b.Property<int>("VariantId")
                        .HasColumnType("int");

                    b.Property<int>("NFurm")
                        .HasColumnType("int");

                    b.Property<double>("RashGazNaF")
                        .HasColumnType("float");

                    b.Property<double>("RashVodiNaF")
                        .HasColumnType("float");

                    b.Property<double>("Tperepad")
                        .HasColumnType("float");

                    b.Property<double>("TrebZnTeor")
                        .HasColumnType("float");

                    b.Property<bool>("isActual")
                        .HasColumnType("bit");

                    b.HasKey("VariantId", "NFurm");

                    b.ToTable("DanniePoFurmam");
                });

            modelBuilder.Entity("LanceFlow.Models.Entities.DanniePoFurmamDate", b =>
                {
                    b.Property<DateTime>("DateId")
                        .HasColumnType("datetime2");

                    b.Property<int>("NFurm")
                        .HasColumnType("int");

                    b.Property<int>("PechId")
                        .HasColumnType("int");

                    b.Property<double>("RashGazNaF")
                        .HasColumnType("float");

                    b.Property<double>("RashVodiNaF")
                        .HasColumnType("float");

                    b.Property<double>("Tperepad")
                        .HasColumnType("float");

                    b.Property<double>("TrebZnTeor")
                        .HasColumnType("float");

                    b.Property<bool>("isActual")
                        .HasColumnType("bit");

                    b.HasKey("DateId", "NFurm", "PechId");

                    b.ToTable("DanniePoFurmamDate");
                });

            modelBuilder.Entity("LanceFlow.Models.Entities.Pechi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("DiamFurm")
                        .HasColumnType("float");

                    b.Property<int>("NFurm")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("VisFurm")
                        .HasColumnType("float");

                    b.Property<double>("Vpolez")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Pechi");
                });

            modelBuilder.Entity("LanceFlow.Models.Entities.ProcessOfTechnology", b =>
                {
                    b.Property<int>("PechId")
                        .HasColumnType("int");

                    b.Property<int>("VariantId")
                        .HasColumnType("int");

                    b.Property<double>("DavlDut")
                        .HasColumnType("float");

                    b.Property<double>("Proizv")
                        .HasColumnType("float");

                    b.Property<double>("RashDut")
                        .HasColumnType("float");

                    b.Property<double>("SodKislorod")
                        .HasColumnType("float");

                    b.Property<double>("TDut")
                        .HasColumnType("float");

                    b.Property<double>("UdRashKoks")
                        .HasColumnType("float");

                    b.Property<double>("VlazDut")
                        .HasColumnType("float");

                    b.HasKey("PechId", "VariantId");

                    b.ToTable("ProcessOfTechnology");
                });

            modelBuilder.Entity("LanceFlow.Models.Entities.ProcessOfTechnologyDate", b =>
                {
                    b.Property<int>("PechId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateId")
                        .HasColumnType("datetime2");

                    b.Property<double>("DavlDut")
                        .HasColumnType("float");

                    b.Property<double>("Proizv")
                        .HasColumnType("float");

                    b.Property<double>("RashDut")
                        .HasColumnType("float");

                    b.Property<double>("SodKislorod")
                        .HasColumnType("float");

                    b.Property<double>("TDut")
                        .HasColumnType("float");

                    b.Property<double>("UdRashKoks")
                        .HasColumnType("float");

                    b.Property<double>("VlazDut")
                        .HasColumnType("float");

                    b.HasKey("PechId", "DateId");

                    b.ToTable("ProcessOfTechnologyDate");
                });

            modelBuilder.Entity("LanceFlow.Models.Entities.Variants", b =>
                {
                    b.Property<int>("VariantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VariantId");

                    b.ToTable("Variants");
                });
#pragma warning restore 612, 618
        }
    }
}
